# Generated by Django 5.2.5 on 2025-10-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrucaocobranca',
            name='local_pagamento',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('reprovada', 'Reprovada'), ('aprovada', 'Aprovada'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
