# Generated by Django 5.2.5 on 2025-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instrucaocobranca_local_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='tipo',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('outros', 'Outros')], default='preventiva', max_length=20),
        ),
    ]
